### ISSUE TITLE
[Issue]: GroupChat doesn't work well

### ISSUE THREAD

**Issue by wxl-lxw** [microsoft/autogen#3462] opened 2024-09-02 04:43 UTC
### Describe the issue

Hi! I want to build a simple group chat using local LLMs, but it raised an error:

```
User_proxy (to chat_manager):

Who are you?

--------------------------------------------------------------------------------
GroupChat is underpopulated with 2 agents. Consider setting speaker_selection_method to 'round_robin' or allow_repeat_speaker to False, or use direct communication, unless repeated speaker is desired.
[autogen.oai.client: 09-02 04:34:22] {329} WARNING - Model /home/xw249/Meta-Llama-3-8B-Instruct is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: small model

[autogen.oai.client: 09-02 04:34:25] {329} WARNING - Model /home/xw249/Meta-Llama-3-8B-Instruct is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
small model (to chat_manager):

Hi! My name is Mia, and I'm a high school student. I'm a junior, to be exact. I'm 16 years old and I'm really passionate about learning. I'm a bit of a bookworm and I love studying languages, history, and literature. I'm also part of the school debate team and I enjoy arguing about current events and social issues. When I'm not in school, I like to hang out with my friends, watch movies, and play video games.

--------------------------------------------------------------------------------
GroupChat is underpopulated with 2 agents. Consider setting speaker_selection_method to 'round_robin' or allow_repeat_speaker to False, or use direct communication, unless repeated speaker is desired.
Traceback (most recent call last):
  File "/home/xw249/Multi-LLM/test.py", line 57, in <module>
    user_proxy.initiate_chat(
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1096, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 732, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 896, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 2050, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 1099, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 538, in select_speaker
    return self._auto_select_speaker(last_speaker, selector, messages, agents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 659, in _auto_select_speaker
    result = checking_agent.initiate_chat(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1089, in initiate_chat
    self.send(msg2send, recipient, request_reply=True, silent=silent)
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 732, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 896, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 2050, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1418, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1437, in _generate_oai_reply_from_client
    response = llm_client.create(
               ^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/oai/client.py", line 735, in create
    response = client.create(params)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/autogen/oai/client.py", line 320, in create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/xw249/miniconda3/envs/Multi-LLM/lib/python3.11/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': '[{\'type\': \'literal_error\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'role\'), \'msg\': "Input should be \'system\'", \'input\': \'user\', \'ctx\': {\'expected\': "\'system\'"}}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_calls\'), \'msg\': \'Extra inputs are not permitted\', \'input\': []}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_calls\'), \'msg\': \'Extra inputs are not permitted\', \'input\': []}, {\'type\': \'literal_error\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'role\'), \'msg\': "Input should be \'assistant\'", \'input\': \'user\', \'ctx\': {\'expected\': "\'assistant\'"}}, {\'type\': \'literal_error\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'role\'), \'msg\': "Input should be \'tool\'", \'input\': \'user\', \'ctx\': {\'expected\': "\'tool\'"}}, {\'type\': \'missing\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_call_id\'), \'msg\': \'Field required\', \'input\': {\'content\': "Hi! My name is Mia, and I\'m a high school student. I\'m a junior, to be exact. I\'m 16 years old and I\'m really passionate about learning. I\'m a bit of a bookworm and I love studying languages, history, and literature. I\'m also part of the school debate team and I enjoy arguing about current events and social issues. When I\'m not in school, I like to hang out with my friends, watch movies, and play video games.", \'tool_calls\': [], \'role\': \'user\', \'name\': \'small model\'}}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_calls\'), \'msg\': \'Extra inputs are not permitted\', \'input\': []}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'name\'), \'msg\': \'Extra inputs are not permitted\', \'input\': \'small model\'}, {\'type\': \'literal_error\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'role\'), \'msg\': "Input should be \'function\'", \'input\': \'user\', \'ctx\': {\'expected\': "\'function\'"}}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_calls\'), \'msg\': \'Extra inputs are not permitted\', \'input\': []}, {\'type\': \'extra_forbidden\', \'loc\': (\'body\', \'messages\', 2, \'typed-dict\', \'tool_calls\'), \'msg\': \'Extra inputs are not permitted\', \'input\': []}]', 'type': 'BadRequestError', 'param': None, 'code': 400}
```

### Steps to reproduce

First, I use vLLM to load my model:
```
vllm serve /home/xw249/Meta-Llama-3-8B-Instruct --dtype=half --max_model_len=2048
```

Then, I use the following code to build a simple multi-agent GroupChat:

```
import autogen
local_llm_config={
    "config_list": [
        {
            "model": "/home/xw249/Meta-Llama-3-8B-Instruct", # Same as in vLLM command
            "api_key": "NotRequired", # Not needed
            "base_url": "http://localhost:8000/v1"  # Your vLLM URL, with '/v1' added
        }
    ],
    "cache_seed": None, # Turns off caching, useful for testing different models
    "temperature": 1
}
user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={
        "last_n_messages": 2,
        "work_dir": "groupchat",
        "use_docker": False,
    },  # Please set use_docker=True if docker is available to run the generated code. Using docker is safer than running the generated code directly.
    human_input_mode="TERMINATE",
)
small = autogen.AssistantAgent(name="small model",
                       max_consecutive_auto_reply=2,
                       system_message="You should act as a student!",
                       llm_config=local_llm_config)

big = autogen.AssistantAgent(name="big model",
                     max_consecutive_auto_reply=2,
                     system_message="Act as a teacher.",
                     llm_config=local_llm_config)
groupchat = autogen.GroupChat(agents=[user_proxy, small, big], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=local_llm_config)
user_proxy.initiate_chat(
    manager, message="Who are you?"
)
```

I am a beginner using AutoGen and don't know how to deal with this exception. Thanks for your patience and looking forward to your early reply!

**Comment by ABD07xx** [comment] 2024-09-02 07:04
groupchat = autogen.GroupChat(
    agents=[user_proxy, small, big],
    messages=[],
    max_round=12,
    speaker_selection_method='round_robin',  # Add this line
    allow_repeat_speaker=False  
)

**Comment by Hk669** [comment] 2024-09-02 11:04
@wxl-lxw i think the issue is with the config_list and the above code sample shows the working code, im closing this for now. 
thanks @ABD07xx for helping with the updated code.

**Closed by Hk669** 2024-09-02 11:04 UTC
