### ISSUE TITLE
cache_seed None doesn't prevent cache file creation in 0.2.0b5

### ISSUE THREAD

**Issue by mathieuisabel** [microsoft/autogen#703] opened 2023-11-17 03:20 UTC
It appears that using cache_seed=None in the llm_config doesn't prevent the .cache directory and sub-content from being created.

I used the config based on what I found here
https://github.com/microsoft/autogen/blob/841b533da8c1902b2d8f83793168a76d0f182a5e/autogen/oai/client.py#L197C11-L199C37

![image](https://github.com/microsoft/autogen/assets/15805484/8eeda3dc-c978-494e-9c3c-1f0151fb9d27)

In 0.14 I was able to use use_cache=False succesfully.

The use case for this is when Autogen is hosted in Azure Functions using a read-only file system.
If external caching mechanisms could be used i.e. Azure Redis, that would be ideal. In the interim, preventing any attempt at writing to the local filesystem would do.

**Comment by afourney** [comment] 2023-11-17 04:06
I believe this is a duplicate of #679

**Comment by sonichi** [comment] 2023-11-17 12:41
Agree with this issue. Unfortunately I don't have time to fix it recently. PRs are welcome. Supporting external caching like Azure Redis would be a good feature to add.

**Comment by afourney** [comment] 2023-11-17 15:49
> Agree with this issue. Unfortunately I don't have time to fix it recently. PRs are welcome. Supporting external caching like Azure Redis would be a good feature to add.

Ok, I'll see if I can push a PR to disable the creation of the DB when cache_seed is None. This won't go so far as to enable remote cache though -- that will need to be a different PR.

**Comment by afourney** [comment] 2023-11-18 00:45
@mathieuisabel please see PR #707 and let me know if it works for you.

**Closed** 2023-11-20 20:39 UTC
Labels: duplicate
