### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by ragesh2000** [microsoft/autogen#984] opened 2023-12-14 12:10 UTC
### Describe the bug

Got an error in autogen groupchat  when i set human_input_mode == 'NEVER'
```
 File "/home/gpu/ai/llm/autogen/autogen_inference.py", line 47, in <module>
    res = user_proxy.initiate_chat(manager, message=msg)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 550, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 348, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 481, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 940, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/groupchat.py", line 291, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/groupchat.py", line 168, in select_speaker
    final, name = selector.generate_oai_reply(
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 625, in generate_oai_reply
    response = client.create(
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/oai/client.py", line 262, in create
    self._update_usage_summary(response, use_cache=False)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/oai/client.py", line 362, in _update_usage_summary
    self.total_usage_summary = update_usage(self.total_usage_summary)
  File "/home/gpu/miniconda3/envs/autogen/lib/python3.10/site-packages/autogen/oai/client.py", line 355, in update_usage
    "completion_tokens": usage_summary.get(response.model, {}).get("completion_tokens", 0)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

```[tasklist]
### Tasks
```

**Comment by afourney** [comment] 2023-12-14 17:13
@ragesh2000 what version of AutoGen are you using?

**Comment by ragesh2000** [comment] 2023-12-15 05:40
pyautogen==0.2.1 is the version iam using @afourney

**Comment by mongolu** [comment] 2023-12-15 08:22
+1 here.
0.2.2 pyautogen

**Comment by kevin666aa** [comment] 2023-12-15 18:32
@ragesh2000 @mongolu Any code that I could replicate the error?

**Comment by mongolu** [comment] 2023-12-16 07:22
In file `autogen/oai/client.py`, I've replace line 365 with this
`"completion_tokens": usage_summary.get(response.model, {}).get("completion_tokens", 0) **if usage_summary.get(response.model, {}).get("completion_tokens", 0) is not None else 0**`

I'm not confident i cant help with the error replication.
I am running autogen in ollama docker container, with `litellm`.

If I can help more, please guide me to give you what info you require.

**Comment by ragesh2000** [comment] 2023-12-16 14:52
I can also provide my code 
`import autogen

config_list_llama = [
    {
        'base_url': "http://0.0.0.0:8000",
        'api_key': "NULL"
    }
]

llm_config_llama = {
    "config_list": config_list_llama,
}

user_proxy = autogen.UserProxyAgent(
   name="User_proxy",
   system_message="A human admin.",
   human_input_mode="NEVER",
)

analyser = autogen.AssistantAgent(
    name="Data analyser",
    llm_config=llm_config_llama,
)
critic = autogen.AssistantAgent(
    name="Critic",
    llm_config=llm_config_llama,
)

groupchat = autogen.GroupChat(agents=[user_proxy, analyser, critic], messages=[], max_round=10)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config_llama)
msg = """Download data from /data/inference_generation_sheet.csv and give me some valuable inferences.
      """
res = user_proxy.initiate_chat(manager, message=msg)`

Iam also using autogen using ollama models and with litellm @kevin666aa

**Comment by kevin666aa** [comment] 2023-12-18 03:33
Thanks! @ragesh2000 @mongolu Can you checkout #1008 and maybe copy paste the code to see if it works? I cannot replicate these errors quickly since I am not using local models.

**Comment by ragesh2000** [comment] 2023-12-18 06:24
Yes that solves my issue @kevin666aa

**Comment by ragesh2000** [comment] 2023-12-18 06:27
Also I have noticed that if the message to user_proxy.initiate_chat is same, the agent is not caring about the message and just returning the previous response. I think some kind of cache is getting involved in the response generation. How can i solve this issue ?

**Comment by mongolu** [comment] 2023-12-18 06:29
Delete .cache dir

**Comment by mongolu** [comment] 2023-12-18 08:58
> Yes that solves my issue @kevin666aa

I also confirm that the problem is solved with this.

**Comment by kevin666aa** [comment] 2023-12-19 03:23
Thanks! Will get it merged!

**Comment by ragesh2000** [comment] 2023-12-19 05:06
Thanks @kevin666aa

**Closed** 2024-01-04 00:43 UTC
Labels: bug, group chat
