### ISSUE TITLE
The agent stops only when the number of sessions reaches the upper limit（Commenting system_message also doesn't work unless max_consecutive_auto_reply is modified）

### ISSUE THREAD

**Issue by lihui123456** [microsoft/autogen#907] opened 2023-12-07 08:48 UTC
chatbot = autogen.AssistantAgent(
    name="chatbot",
    system_message="For coding tasks, only use the functions you have been provided with. Reply TERMINATE when the task is done.",
    llm_config=llm_config,
)

# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    code_execution_config={"work_dir": "coding"},
)

# start the conversation
user_proxy.initiate_chat(
    chatbot,
    message="你知道中国的首都是哪里.",
)

Reply：
user_proxy (to chatbot):

你知道中国的首都是哪里.

--------------------------------------------------------------------------------
chatbot (to user_proxy):

中国的首都是北京。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

有什么我可以帮助你的吗？

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你有任何问题或需要帮助，请随时提问。我会尽力回答你的问题。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你需要了解一些关于中国的信息，比如地理、历史、文化等方面的内容，我可以帮助你。或者如果你有其他任何问题或需要帮助，也请告诉我。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你对中国的旅游景点、美食、传统节日等方面有兴趣，我也可以提供相关的信息给你。只需告诉我你感兴趣的方面，我会尽力为你提供帮助。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你有任何其他问题或需要帮助，请随时告诉我。我会尽力回答你的问题。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你有任何问题或需要帮助，请随时提问。我会尽力回答你的问题。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你对中国的任何方面有任何问题或需要帮助，请告诉我。我会尽力回答你或提供帮助。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你还有其他问题或需要帮助，请随时告诉我。我会尽力回答你的问题。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你有任何问题或需要帮助，请随时提问。我会尽力回答你的问题。

--------------------------------------------------------------------------------
user_proxy (to chatbot):

--------------------------------------------------------------------------------
chatbot (to user_proxy):

如果你有任何问题或需要帮助，请随时告诉我。我会尽力回答你的问题。

--------------------------------------------------------------------------------

**Comment by rickyloynd-microsoft** [comment] 2023-12-07 15:01
@lihui123456, the title is unclear to me. Can you provide a more detailed description of the problem, as well as an example in English?

**Comment by lihui123456** [comment] 2023-12-08 00:53
@rickyloynd-microsoft 
If max_consecutive_auto_reply is not consecuTIVE_0, for example, if I set max_consecutive_auto_reply=10, the number of sessions on the agent will not be stopped until 10 rounds, and the first round of conversations meets the expectation, but the subsequent ones are not. How can I solve this problem

here is my code
chatbot = autogen.AssistantAgent(
    name="chatbot",
    system_message="Your loyal assistant! Reply `TERMINATE` in the end when everything is done..",
    llm_config=llm_config,
)

# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    # is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
    is_termination_msg=lambda msg: "TERMINATE" in msg["content"],
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    code_execution_config={"work_dir": "coding"},


# start the conversation
user_proxy.initiate_chat(
    chatbot,
    message="hello.",
)



here is Dialogue
user_proxy (to chatbot):

hello.

--------------------------------------------------------------------------------
chatbot (to user_proxy):

Hello! How can I assist you today?

--------------------------------------------------------------------------------
user_proxy (to chatbot):



--------------------------------------------------------------------------------
chatbot (to user_proxy):

It looks like you haven't entered any text. If you have any questions or need assistance with anything, feel free to let me know. I'm here to help!

--------------------------------------------------------------------------------
user_proxy (to chatbot):



--------------------------------------------------------------------------------
chatbot (to user_proxy):

It seems there might be an issue with your messages coming through. If you're trying to communicate with me, please try to send your message or question again, and I'll do my best to assist you. If you're simply testing how I respond to no input, well, here's your answer! I'm here and ready to help whenever you need.

--------------------------------------------------------------------------------
user_proxy (to chatbot):



--------------------------------------------------------------------------------
chatbot (to user_proxy):

If you're encountering any issues or have questions, please make sure to type them out so I can assist you. Otherwise, if you're just exploring how the system works, feel free to type 'hello' or any other message, and we can continue our interaction. I'm here to help with whatever you need!

--------------------------------------------------------------------------------
user_proxy (to chatbot):



--------------------------------------------------------------------------------
chatbot (to user_proxy):

It appears you may have difficulties sending messages or there might be an error. If you have a specific question or need help with a task, please try to type it again. If this is a test or if you're done, you can also type "TERMINATE" to end our conversation. Let me know if there's anything I can do for you!

thanks

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 01:46
Thanks for the extra info. It seems that you want the chat to terminate earlier, and you tell the assistant (in its system prompt) that it can end the chat by replying `TERMINATE`. But telling the assistant that it has the ability to terminate the chat does not actually give the assistant that ability. And since `human_input_mode="NEVER"`, the user has no opportunity to type `exit` to end the chat. In this case, `UserProxyAgent` serves no purpose except to execute code and report any errors. And yet the initial message passed to `initiate_chat` does not tell the assistant to write any code. Everything proceeds as expected.

As the app designer, what is your high-level goal for configuring the agents in this way? What is the type of behavior you want to produce, or the type of task you want the agents to solve together?

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 02:14
You say that "normal chat conversations don't end in ten rounds but end in the first round and return the most reliable responses." If you want to write an app to behave in that way, you can pass `max_consecutive_auto_reply=0` to `UserProxyAgent`. Or you can completely omit any `UserProxyAgent` from your code and simply pass the question or task description directly to the assistant, and use the assistant's reply as the answer. Would one of those designs meet your goal?

I don't understand your last sentence at all.

Your second example shows another way that chats can be ended. Your code contains this line:

`is_termination_msg=lambda msg: "TERMINATE" in msg["content"],`

As a result, the assistant successfully ends the chat well before 10 turns by including the string `TERMINATE` in its response. It seems to be working correctly. Or did you intend something different?

**Comment by lihui123456** [comment] 2023-12-08 02:24
@rickyloynd-microsoft What I need is for the number of sessions not to be affected by max_consecutive_auto_reply=10, but rather to be more intelligent, so that for example a problem that requires a consecuTIVE_AUTO_REPLY =10 sessions is solved. The rest is all useless nonsense, meaning that several rounds of dialogue are not limited by the above parameters, but are left to the agent to decide when to end, the above parameters are just to prevent the agent from getting into a constant loop. thanks

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 02:44
Your example above shows the agent successfully deciding when to end the chat after a few turns, much less than 10. But your example doesn't involve a problem at all. Suppose that you started it with "What is 2+3?" instead of "hello". The assistant would reply "5". But the user_proxy would still reply with nothing, because there is no code to execute. 

To further reduce the number of turns, you could modify the assistant's system prompt to say "When you have answered the question or solved the problem, append TERMINATE to your response to end the chat". Then the assistant may reply something like "5 TERMINATE" which would end the chat with no extra turns. Is there some other behavior you would want?

**Comment by lihui123456** [comment] 2023-12-08 02:59
@rickyloynd-microsoft What about that hello I asked about above? Or how do we solve this problem, I don't want me to consecutive_AUTO_REPLY and the conversation stops after one round if I consecutive_CONSECUTIVE_REPLY parameters can't be changed thanks

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 04:51
What behavior would you expect in the "Hello" chat above? Which agent would you like to see terminate the chat, and at exactly which point?

**Comment by lihui123456** [comment] 2023-12-08 05:52
@rickyloynd-microsoft 
here is Dialogue
user_proxy (to chatbot):

hello.

chatbot (to user_proxy):

Hello! How can I assist you today?

My expectation is to stop in the first round of conversation 
thanks

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 14:44
Are you saying that every conversation should stop right after the assistant says "How can I assist you today"? Why would anyone expect the conversation stop at this point? What if the user responds to the assistant by saying "Please write code to..."? I must be missing something that you have in mind.

**Comment by rickyloynd-microsoft** [comment] 2023-12-08 15:06
Maybe your point is that it never makes sense for an agent to output an empty response, so if it's about to do that, the agent should always terminate the chat instead. Would that extra termination condition produce the behavior you expect?

**Comment by rickyloynd-microsoft** [comment] 2023-12-09 22:49
@lihui123456, unless you have more to add, I'm going to open a separate issue regarding the empty responses from user_proxy, where we can discuss how best to improve the behavior. Then I'll close this issue and add a link to it in the new issue.

**Comment by ruifengma** [comment] 2023-12-14 08:48
@rickyloynd-microsoft I think that the higher-level problem @lihui123456 mentioned is that even if the task has been done perfectly, the termination mechanism is still not as smart as expected. This is always happens when the LLM model is not as powerful as GPT-4. And there is also a similar case which mentioned in the Autogen documentation website [https://microsoft.github.io/autogen/docs/FAQ/](url) which is the agent keep thank to each other even when the task has been finished. The suggestion is to add termination notice at the end of the prompt. I think you may also able to modify it to your case to see what will happen.

**Comment by lihui123456** [comment] 2023-12-14 08:53
@ruifengma 
I added a termination notification when the problem is resolved to the prompt, but the feeling doesn't end, it's still the same

**Comment by ruifengma** [comment] 2023-12-14 08:58
@lihui123456 what's your termination notification looks like?

**Comment by lihui123456** [comment] 2023-12-14 09:01
@lihui123456 When you have answered the question or solved it, add TERMINATE to your answer to end the chat    this is ok?

**Comment by lihui123456** [comment] 2023-12-14 09:14
@ruifengma this is  a "gratitude loop"

**Comment by rickyloynd-microsoft** [comment] 2023-12-14 15:11
> @rickyloynd-microsoft I think that the higher-level problem @lihui123456 mentioned is that even if the task has been done perfectly, the termination mechanism is still not as smart as expected. This is always happens when the LLM model is not as powerful as GPT-4. And there is also a similar case which mentioned in the Autogen documentation website [https://microsoft.github.io/autogen/docs/FAQ/](url) which is the agent keep thank to each other even when the task has been finished. The suggestion is to add termination notice at the end of the prompt. I think you may also able to modify it to your case to see what will happen.

@ruifengma  It's certainly true that intelligent termination and gratitude loops are challenges that we need better solutions to. And empty responses are another area of potential improvement. To make progress we need concrete examples where we know what behavior would be better than the current behavior. That's what I don't see in the example presented in this issue. The agent is not presented with a task or problem to solve; instead, the user_proxy simply says "hello". The assistant responds in reasonable ways, and after a few turns triggers the TERMINATE condition as expected, well before the maximum number of turns. The user_proxy responds with empty strings because the human user is never allowed to exit the chat manually, and no LLM is attached to the user_proxy, so its responses cannot be intelligent. It's not clear why the user_proxy agent is chosen at all in this example. In my view, since the expected behavior is unclear, this example gives us no guidance for making improvements. I would welcome a clearer example, centered on an actual task, and probably presented in a separate issue for simplicity.

**Comment by mferris77** [comment] 2023-12-14 21:29
Perhaps I can add some helpful details here, as I just came across this thread while investigating a similar error. I'm not sure if it completely aligns with the original issue above but given the confusion perhaps my experience can help with the issue.

I have been following Autogen developments for some time now but am only now getting my hands dirty.  I'm testing out some of the demo notebooks, and am currently working through 'agentchat_groupchat_RAG.ipynb' as it contains features I would like to implement for a project I'm working on.  I am also connecting to a local LLM running on LM Studio, perhaps that is a key detail.

When I run the 'rag_chat' function, which is set up with a boss_aid (rag proxy), coder, pm and reviewer in a 'round_robin' speaker selection method, so agents will speak in that order.  I'm only asking a question about the local documents, not asking for code.

All goes well - RAG agent collects some documents, sends the request off to the LLM, we get back a response. Next up is the coder, who basically summarizes the original response.  Then the PM who formats the information into a proper response to my original question.  Finally code_reviewer adds their feedback saying the summary is accurate.  No one has said 'terminate' yet and human interaction is 'never', so next up is the RAG agent (boss_aid), who simply responds with an empty string, which appears to be the default for RetrieveUserProxyAgent.  I'm not sure if this is an LM Studio thing, but I get back an error saying `Error code: 400 - {'error': "'messages' array must only contain objects with a 'content' field that is not empty.`.  In the LM Studio console I can see that the last message was indeed an empty content string from the 'Boss_assistant'.

So my thought here is that the assistant should not respond with nothing but rather the same message others have (reply terminate if task is done).  That's what would be sent to the LLM in the event that there's no other messages to send.  Either that or the RAG agent shouldn't be in the group chat and it communicates via function calls from the other agents (the last example in the notebook).  Or maybe the default reply should be something along the lines of "reply 'terminate' when everything is done, or 'update context' if you need more information'.

**Comment by rickyloynd-microsoft** [comment] 2023-12-14 22:55
> Perhaps I can add some helpful details here, as I just came across this thread while investigating a similar error. I'm not sure if it completely aligns with the original issue above ...

@mferris77  Thanks for the concrete example! Group chats are especially complex, glad you found a way to make it work. I can't tell whether your example addresses the concern that prompted the creation of this issue, so I'm going to close this issue and thank everyone involved in the discussion. You're all invited to open a separate issue if you can find a clear example of a specific problem for us to work on solving.

**Closed by rickyloynd-microsoft** 2023-12-14 22:55 UTC

**Comment by dimknaf** [comment] 2023-12-29 09:02
@mferris77 Can you please explain where I can add this one?
