### ISSUE TITLE
chromadb hardcoded path doesn't work in rag_chat in in kaggle kernal environment

### ISSUE THREAD

**Issue by Owaiskhan9654** [microsoft/autogen#444] opened 2023-10-26 20:57 UTC
https://github.com/microsoft/autogen/blob/50ac5476377c1b41330589a6cfc5c4e65b93079f/autogen/retrieve_utils.py#L353

<img width="1728" alt="image" src="https://github.com/microsoft/autogen/assets/47840160/6a21fe51-2049-46ea-8abc-2b047cd80595">

Can we somehow set this path for chromadb dynamically. Tried using changing the path in client path in below code in retrieve_config but that doesn't seems to be reflecting.

` retrieve_config={
        "task": "code",
        "docs_path": "Somelink",
        "chunk_token_size": 1000,
        "model": config_list[0]["model"],
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        "collection_name": "groupchat",
        "get_or_create": True,
    },
` 

@sonichi @qingyun-wu @thinkall 

Also this commit doesn't seems to work which was merged 2 days back

Fix tmp dir not exists https://github.com/microsoft/autogen/pull/401

**Comment by gagb** [comment] 2023-10-26 22:48
@thinkall seems like the issue is that while `db_path` is an argument in `query_vector_db`, the function that calls it i.e.,`retrieve_docs` does not take `db_path` as input. Is that correct?

**Comment by thinkall** [comment] 2023-10-27 01:26
@Owaiskhan9654 @gagb  Thanks for the good catch. I pushed a fix to #435 

#401 doesn't work in your env? What's the error message? The folder creation failed?

**Closed** 2023-10-27 03:02 UTC
