### ISSUE TITLE
Config Issues only occurring with azure

### ISSUE THREAD

**Issue by nickgannon10** [microsoft/autogen#260] opened 2023-10-16 15:21 UTC
Hi, hope everything is going well. I've triple checked, and for some reason if I set my config list to my open ai api key, everything works swimmingly, but if I set it to my azure api key, I receive the error below. I'm confident the azure api instance is working properly. If you have any opinions about how to resolve this issue, I'd be excited to hear them. 

InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

- this config list works
config_list = [{'model': 'gpt-4', 'api_key': {my open api key} }]

- this one does not
config_list = [{'model': 'gpt-4-32k', 'api_key': {azure api key}, 'api_base': {azure api base}, 'api_type': 'azure', 'api_version': '2023-07-01-preview'}]

assistant = AssistantAgent(name="assistant", llm_config={"config_list": config_list})

**Comment by sonichi** [comment] 2023-10-16 15:46
Please make sure the model name matches the deployment name. One thing you can do is to try the same config with `openai.ChatCompletion.create` to verify the config is correct.

**Comment by nickgannon10** [comment] 2023-10-16 17:18
That was totally my issue, I was putting in model type rather than deployment name. 

This was tremendously helpful. Thank you for your quick response!

Have a great day!

**Comment by qingyun-wu** [comment] 2023-10-17 14:53
Closing the issue as the problem is solved! Thank you both!

**Closed by qingyun-wu** 2023-10-17 14:53 UTC
