### ISSUE TITLE
Issue with OLLAMA methods and proxy with autogen

### ISSUE THREAD

**Issue by athmanar** [microsoft/autogen#3936] opened 2024-10-23 23:07 UTC
### What happened?

I have a ollama serve running on a local machine.  The server works fine and I can run ollama run from the command line without any issues.
in the `/etc/systemd/system/ollama.service` the proxy environments are setup correctly.

```
Environment="http_proxy=$$$$$.com:port"  #                            
Environment="https_proxy=$$$$$.com:port"  #   
```

Now in Autogen when you define the ollama model using the following format[from ollama tutorial]:

```
ollamakey="http://localhost:11434/v1"
config_list=[{"model": "llama3:70b-instruct", "base_url": ollamakey, 'api_key': 'ollama', "price": [0, 0]} ] 
autogen.AssistantAgent(name=name, llm_config={ "cache_seed": cache_seed, "config_list": config_list, }, system_message=system_message)
# THIS WORKS!
```
I am guessing this is called using the openAI wrapper and seems to understand the proxy settings.

Now this does not work and gets forbidden:
```
ollamakey="http://localhost:11434/v1"
config_list=[{"model": "llama3:70b-instruct","client_host": ollamakey, 'api_type': 'ollama',"stream": False,} ] # ONLY change here
autogen.AssistantAgent(name=name, llm_config={ "cache_seed": cache_seed, "config_list": config_list, }, system_message=system_message)
```
My guess is this is using the Ollama curl/Post commands to interact and for some reason cannot understand the proxy variables. I followed the tutorial given here: [link to notebook](https://github.com/microsoft/autogen/blob/0.2/website/docs/topics/non-openai-models/local-ollama.ipynb
)
In this case it does not connect and gives the error:
```
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 2056, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 1110, in run_chat
    reply = speaker.generate_reply(sender=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 2056, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1424, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1443, in _generate_oai_reply_from_client
    response = llm_client.create(
               ^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/oai/client.py", line 766, in create
    response = client.create(params)
               ^^^^^^^^^^^^^^^^^^^^^
  File "envs/llm-mcts/lib/python3.11/site-packages/autogen/oai/ollama.py", line 235, in create
    raise RuntimeError(f"Ollama exception occurred: {e}")
RuntimeError: Ollama exception occurred: 404 page not found

```

If I  change the `config_list = [{"model": "llama3:70b-instruct", 'api_type': 'ollama',"stream": False,} ] # NO client_host given`

Then I get this message that looks like html of forbidden proxy:
` </style> <title> 403 Forbidden: incorrect proxy service was requested </title> </head> <body> <div class="message-container">
`

Something is not correct with ollama and autogen calls. Is there a way to set the environment proxy variables? Or are these errors completely different

### What did you expect to happen?

I expected no be able to connect using both the methods provided.

### How can we reproduce it (as minimally and precisely as possible)?

Try this : 

DOES NOT WORK:
```
ollamakey="http://localhost:11434/v1"
config_list=[{"model": "llama3:70b-instruct","client_host": ollamakey, 'api_type': 'ollama',"stream": False,} ] # ONLY change here
autogen.AssistantAgent(name=name, llm_config={ "cache_seed": cache_seed, "config_list": config_list, }, system_message=system_message)
```

Try this:
THIS WORKS!
```
ollamakey="http://localhost:11434/v1"
config_list=[{"model": "llama3:70b-instruct", "base_url": ollamakey, 'api_key': 'ollama', "price": [0, 0]} ] 
autogen.AssistantAgent(name=name, llm_config={ "cache_seed": cache_seed, "config_list": config_list, }, system_message=system_message)
```

Try this:

DOES NOT WORK: For a different reason(proxy)

```
config_list = [{"model": "llama3:70b-instruct", 'api_type': 'ollama',"stream": False,} ]
autogen.AssistantAgent(name=name, llm_config={ "cache_seed": cache_seed, "config_list": config_list, }, system_message=system_message)
```

### AutoGen version

autogen.__version__ '0.3.0'

### Which package was this bug in

Core

### Model used

llama 70B

### Python version

Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux

### Operating system

Linux

### Any additional info you think would be helpful for fixing this bug

PLease let me know why this is happening.

**Comment by ekzhu** [comment] 2024-10-24 13:29
@marklysze I had it working without the proxy host. Is it something you can comment on?

**Comment by ekzhu** [comment] 2024-10-24 13:37
Dear @athmanar, our package is `autogen-agentchat` and the latest stable release is `0.2.37`. Can you check if the issue is fixed in the latest release? 

We don't maintain the `autogen` package.

**Comment by athmanar** [comment] 2024-10-24 18:27
@ekzhu  I am quite confused as this is the autogen github repo. So can you please point me to the correct place to ask this question.

I observed that if the client_host: `http://localhost:11434` the proxy works. and everything runs smoothly
However if I use `http://localhost:11434 :v1` as per the autogen library it does not work. It probably is an issue with ollama agent class implementation.

**Comment by marklysze** [comment] 2024-10-24 18:55
@athmanar, the `autogen` package is from this repo, https://github.com/autogenhub/autogen

I think the Ollama implementations are fairly similar.

**Closed** 2024-10-24 21:38 UTC
Labels: needs-triage
