### ISSUE TITLE
Allow for get_human_input to be async

### ISSUE THREAD

**Issue by constantinidan** [microsoft/autogen#527] opened 2023-11-02 23:59 UTC
Hi!

Ideally the `get_human_input` should also have the ability to be async. Right now, it seems impossible to have a code that is fully async because of this.

To do that, there is a need to async the function `check_termination_and_human_reply` and await the three calls to `get_human_input`

Thanks

**Comment by sonichi** [comment] 2023-11-04 04:49
This feature is added in [v0.2.0b1](https://github.com/microsoft/autogen/discussions/546). Could you test it?

**Comment by my3sons** [comment] 2024-02-24 15:49
Hello, just curious if anyone ever had complete success with this? I was recently trying to go all async with a chainlit/autogen implementation but ran into this issue. I tried running with v0.2.0b1 and I got a bit further downstream but then ran into this:

```
Traceback (most recent call last):
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "main.py", line 121, in on_chat_start
    await user_proxy.a_initiate_chat(
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 563, in a_initiate_chat
    await self.a_send(self.generate_init_message(**context), recipient, silent=silent)
  File "main.py", line 95, in a_send
    await super(ChainlitUserProxyAgent, self).a_send(
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 389, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 509, in a_receive
    await self.a_send(reply, sender, silent=silent)
  File "main.py", line 42, in a_send
    await super(ChainlitAssistantAgent, self).a_send(
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 389, in a_send
    await recipient.a_receive(message, self, request_reply, silent)
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 509, in a_receive
    await self.a_send(reply, sender, silent=silent)
  File "main.py", line 95, in a_send
    await super(ChainlitUserProxyAgent, self).a_send(
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 387, in a_send
    valid = self._append_oai_message(message, "assistant", recipient)
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 281, in _append_oai_message
    message = self._message_to_dict(message)
  File "/Users/carey/PycharmProjects/chainlit-async/venv/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 263, in _message_to_dict
    return dict(message)
TypeError: 'coroutine' object is not iterable
```

**Comment by sonichi** [comment] 2024-02-25 18:26
Could you try the latest version? v0.2.15.

**Comment by my3sons** [comment] 2024-02-26 13:42
Hello @sonichi, I upgraded to v0.2.15 and again using the autogen example from the chainlit cookbook with human_input_mode="ALWAYS", I am running into this the first time the user_proxy asks for feedback. If I simply return and go with auto_reply, the following message gets created:

`{'role': 'user', 'content': <coroutine object ChainlitUserProxyAgent.get_human_input at 0x10b975cc0>}`

That message ultimately ends up in autogen/code_utils and fails at line 65 because of the coroutine type:

```
if content is None:
    return ""
if isinstance(content, str):
    return content
if not isinstance(content, list):
    raise TypeError(f"content must be None, str, or list, but got {type(content)}")
```

I am continuing to look into this but if anything comes to mind for you, please let me know. Thanks!

**Comment by my3sons** [comment] 2024-02-28 12:59
Hello @sonichi, I finally found some time to look into this further and the issue is solely with the chainlit cookbook code and autogen async is working perfectly. I will open a PR on the chainlit side to resolve the issue. Thanks for the work you do with autogen, it is truly exciting to work with these capabilities!

**Comment by julianakiseleva** [comment] 2024-02-29 00:50
@my3sons @constantinidan  can we close this issue?

**Comment by my3sons** [comment] 2024-02-29 12:12
Hello @julianakiseleva , from my perspective, this issue can be closed.

**Closed** 2024-03-01 17:29 UTC
Labels: dev
