### ISSUE TITLE
chromadb fails in codespaces because of old version of sqlite3

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#519] opened 2023-11-01 21:32 UTC
Wonder how much trouble it would be to update the codespace build process to include this fix, so that users don't need to hit the error and find the FAQ workaround themselves.

_Originally posted by @marcgreen in https://github.com/microsoft/autogen/issues/251#issuecomment-1777853310_

**Comment by afourney** [comment] 2023-11-01 23:29
For context the problem is: "chromadb fails in codespaces because of old version of sqlite3"

**Comment by rickyloynd-microsoft** [comment] 2023-11-28 02:00
Duplicate of #251

**Closed by rickyloynd-microsoft** 2023-11-28 02:00 UTC
