### ISSUE TITLE
[.Net][Bug]: AutoGen.SourceGenerator doesn't encode `"` in structural comments 

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#2872] opened 2024-06-06 07:23 UTC
### Describe the bug

When the content in structural comments contains `"`, the generated code won't get compiled because the `"` breaks the string.

**Comment by prithvi2226** [comment] 2024-06-07 14:25
Hi @LittleLittleCloud! This task seems to be interesting! Can I work on this task?

**Comment by LittleLittleCloud** [comment] 2024-06-07 15:47
@prithvi2226 that would be awesome!

**Comment by prithvi2226** [comment] 2024-06-07 15:55
@LittleLittleCloud If possible, could you please assign this task to me? However, if this action doesn't make a significant difference, I am fine with it. The main priority is to ensure the issue is resolved and the repository progresses smoothly.

**Comment by LittleLittleCloud** [comment] 2024-06-20 18:07
@prithvi2226 Any update on this issue

**Comment by prithvi2226** [comment] 2024-06-21 19:52
> @prithvi2226 Any update on this issue

Hey @LittleLittleCloud , I am still working on it, been remote for a while, I can give you an update by Tuesday!? If that's okay?

**Comment by LittleLittleCloud** [comment] 2024-06-30 04:47
@prithvi2226 Do you need more time on this one? Also please let me know if you need help!

**Comment by prithvi2226** [comment] 2024-07-01 07:33
Hi @LittleLittleCloud! Thank you very much for checking up on me, and thank you very much for taking the time to help me out with this. I am very sorry from my side, for not giving an update, to solve this bug.

Please Correct me if I am wrong, I have decided to work on the file `dotnet/src/AutoGen.SourceGenerator/DocumentCommentExtension.cs `, and `DocumentCommentExtension` class contains methods for handling documentation comments, and it's where I am going to add the logic to escape double quotes in the comments. And, in the method 'GetParameterDescriptionFromDocumentationCommentTriviaSyntax' looks like it processes descriptions for parameters from documentation comments. I hope I am on the right track! Thank you very much!

**Comment by LittleLittleCloud** [comment] 2024-07-01 16:02
@prithvi2226 Thanks for your response.

IMO you don't need to go that further into DocumentCommentExtension.cs, the quickest solution is to encode `"` properly in https://github.com/microsoft/autogen/blob/80ecbf900ca9c2bc7db519702ae132ec6b6c6a3f/dotnet/src/AutoGen.SourceGenerator/Template/FunctionCallTemplate.tt#L84. (`"` -> `""`)

For example, when the comment contains `"`
```csharp
/// <summary>
/// I have " in the summary and the generated code is breaking!
/// </summary>
/// <param name="city"></param>
/// <returns></returns>
[Function]
public async Task<string> GetWeatherAsync(string city)
{
    return await Task.FromResult($"The weather in {city} is sunny.");
}
```

The generated code is
![image](https://github.com/microsoft/autogen/assets/16876986/b84e6531-3d6d-4e77-8570-e91f42c184ca)

As you can see, `"` breaks the generated code because `FunctionTemplate.tt` encodes description using `@"...."` and didn't process the `"` in the comment description.


The quickest fix is to encode `"` in description by doubling it (`""`). This is how `"` is encoded as well in [verbatim string](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim).

e.g.
![image](https://github.com/microsoft/autogen/assets/16876986/d0e7085c-4dd3-4fd9-a4c8-39d5fe170c50)

**Comment by prithvi2226** [comment] 2024-07-02 10:37
Hi @LittleLittleCloud ,

Thank you very much for your guidance. Based on your suggestion, I will implement the fix directly in the FunctionCallTemplate.tt file. Here are the steps I plan to take:

Planned Changes:
1. Modify the FunctionCallTemplate.tt File:

Locating the line that assigns the description (around line 84):

 `Description = @"<#=parameter.Description#>",`

2. I will modify this line to properly encode double quotes by doubling them (""), like so:

 `Description = @"<#= parameter.Description.Replace("\"", "\"\"") #>",`

This approach should correctly handle double quotes in comments and prevent the generated code from breaking.

Please let me know if this solution looks good to you, and I will proceed with making these changes.

Thank you once again for your assistance!

Best regards,
Prithvi

**Comment by LittleLittleCloud** [comment] 2024-07-02 17:38
You nailed it!

**Comment by prithvi2226** [comment] 2024-07-03 01:39
Hi @LittleLittleCloud ! I have created a pull request, let me know what you think about it. Thank you very much for your guidance and support. I would love to connect with you on Github or Slack to continue supporting this project.

**Closed** 2024-07-05 23:15 UTC
Labels: bug
